version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo apt-get install python-pip
            sudo pip install -r requirements.txt
      - run:
          name: migrate
          command: |
            python manage.py migrate
      - run:
          name: run tests
          command: |
            python manage.py collectstatic
            python manage.py test
            flake8 --exclude polls/migrations/,manage.py  .

      - run: bash .circleci/setup-heroku.sh
 
      - run: bash .circleci/setup-heroku.sh

      - add_ssh_keys:
          fingerprints:
            - "95:78:98:4a:12:dc:02:f1:86:9e:46:26:f0:3a:fb:b3"
            
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku master -f
            fi